python inference.py \
--image_dir /media/emmahaidacher/Volume/DATASETS/MASTER_DATASETS/cut_roasted_beef/beef_1/ \
--out_dir /media/emmahaidacher/Volume/GOOD_RESULTS/5_videos/ \
--traj_txt test/v2v_trajs/espresso_loop.txt \
--mode single_video_interp \
--seed 123 \
--ckpt_path ./checkpoints/model_16.ckpt \
--config configs/inference_pvd_1024.yaml \
--ddim_steps 50 \
--ddim_eta 0.0 \
--video_length 16 \
--device cuda:0 \
--height 576 \
--width 1024 \
--model_path ./checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth \
--exp_name beef_1 \
--n_frames 16