python inference.py \
--image_dir /media/emmahaidacher/Volume/DATASETS/MASTER_DATASETS/coffee_martini/coffee_1/ \
--out_dir /media/emmahaidacher/Volume/GOOD_RESULTS/ \
--traj_txt test/v2v_trajs/right.txt \
--mode single_video_interp \
--seed 123 \
--ckpt_path ./checkpoints/model_16.ckpt \
--config configs/inference_pvd_1024.yaml \
--ddim_steps 50 \
--ddim_eta 0.0 \
--video_length 16 \
--device cuda:0 \
--height 576 \
--width 1024 \
--model_path ./checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth \
--n_frames 32 \
--unconditional_guidance_scale 1.5 \
--exp_name single_v2v_coffee_cfg_15_msa_all
