python inference.py \
--image_dir     IMAGE_DIR \
--gt_dir        GT_DIR \
--out_dir       OUT_DIR \
--mode          multi_video_interp \
--bg_trd        0.2 \
--seed          123 \
--ckpt_path     ./checkpoints/model_16.ckpt \
--config        configs/inference_pvd_1024.yaml \
--ddim_steps    50 \
--ddim_eta      0.0 \
--temperature   0.0 \
--video_length  16 \
--device        cuda:0 \
--height        576 \
--width         1024 \
--model_path    ./checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth \
--exp_name      EXP_NAME \
--n_frames      NUMBER_FRAMES \
--set_position \
--reuse_guidance_image \
--use_easi3r \
--unconditional_guidance_scale 1.0 \
--use_ddim_inversion \
--use_latent_blending \
--mask_type easi3r_prev